name: Validate C++

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'